import type { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    default: "Admin - Ambiance",
    template: "%s - Ambiance",
  },
  description: "Generated by create next app",
};

export default function BackendLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
